import type { GraphPredicate } from "./types.js";

export const MAX_GRAPH_QUERY_DEPTH = 4;
export const MAX_GRAPH_QUERY_ASSERTIONS = 256;
export const MAX_GRAPH_QUERY_CONSIDERED_ASSERTIONS = 1_024;
export const MAX_GRAPH_QUERY_VISITED_REFS = 1_024;
export const MAX_GRAPH_QUERY_SEEDS = 32;
export const MAX_GRAPH_APPEND_BATCH_ASSERTIONS = 65_536;
export const MAX_GRAPH_ASSERTION_SOURCE_REFS = 128;
export const MAX_ACTIVATION_ESTIMATED_TOKENS = 32_768;
export const GRAPH_ASSERTION_SOURCE_NAMESPACE = "attunegraph.assertion";

export const ACTIVATION_PREDICATES: readonly GraphPredicate[] = Object.freeze([
  "SUPPORTED_BY",
  "DERIVED_FROM",
  "REVISION_OF",
  "SUPERSEDES",
  "GOVERNED_BY",
  "AUTHORIZED_BY",
  "PRODUCED_OUTCOME",
  "PROPOSES_POLICY",
  "SCOPED_TO",
  "NEXT_STEP_FOR",
  "CONTEXT_FOR",
  "LINKED_TO",
  "DELIVERED_FOR",
  "OBSERVED_DURING",
  "PRECEDED",
  "CORRELATES_WITH",
  "PERFORMED"
]);

export const ACTIVATION_PREDICATE_PRIORITY: Readonly<Record<GraphPredicate, number>> = {
  SUPPORTED_BY: 0,
  DERIVED_FROM: 1,
  REVISION_OF: 2,
  SUPERSEDES: 3,
  GOVERNED_BY: 4,
  AUTHORIZED_BY: 5,
  PRODUCED_OUTCOME: 6,
  PROPOSES_POLICY: 7,
  SCOPED_TO: 8,
  NEXT_STEP_FOR: 9,
  CONTEXT_FOR: 10,
  LINKED_TO: 11,
  DELIVERED_FOR: 12,
  OBSERVED_DURING: 13,
  PRECEDED: 14,
  CORRELATES_WITH: 15,
  PERFORMED: 16
};

export const SINGLE_VALUE_PREDICATES: ReadonlySet<GraphPredicate> = new Set([
  "GOVERNED_BY",
  "NEXT_STEP_FOR",
  "PRODUCED_OUTCOME"
]);
