// Curated public surface: named exports only, one block per module,
// limited to symbols actually consumed via "@muse/domain-tools" (or this
// barrel) outside their defining module — internal-only helpers stay
// unexported. See packages/agent-core/src/index.ts for the house style.

export { createBackgroundListTool } from "./background-list-tool.js";
export { detectCalendarConflicts, selectUpcomingConflicts } from "./calendar-conflicts.js";
export type { CalendarConflict, ConflictEventLike } from "./calendar-conflicts.js";
export { createContactsAddTool, createContactsFindTool, createContactsRemoveTool, createUpcomingBirthdaysTool } from "./contacts-tool.js";
export { extractEmailAddress, extractPlainTextBody, GmailAuthError, GmailEmailProvider, summarizeInbox, unreadBriefingLine } from "./email-provider.js";
export type { EmailMessage, EmailProvider, EmailReader, EmailSearcher, EmailSender, EmailSummary } from "./email-provider.js";
export { composeForward, replyEmailWithApproval, replySubject, sendEmailWithApproval } from "./email-send.js";
export type { EmailApprovalGate } from "./email-send.js";
export { createEmailForwardTool, createEmailReadMessageTool, createEmailReadTool, createEmailReplyTool, createEmailSearchTool, createEmailSendTool } from "./email-tool.js";
export { removeRemindersForEvent, rescheduleRemindersForEvent, syncRemindersOnEventDelete } from "./event-reminder-link.js";
export { createFeedsSearchTool } from "./feeds-search-tool.js";
export type { FeedEntryLike } from "./feeds-search-tool.js";
export { createBrowsingSearchTool } from "./browsing-search-tool.js";
export type { BrowsingVisitLike } from "./browsing-search-tool.js";
export { fetchReadableUrl, isPdfContentType, isReadableContentType } from "./fetch-readable-url.js";
export { homeWatchesFromConfig } from "./home-watch.js";
export { createCalendarMcpServer, resolveEventByRef } from "./loopback-calendar.js";
export { createContextReferenceMcpServer } from "./loopback-context.js";
export { createCryptoMcpServer } from "./loopback-crypto.js";
export { createDiffMcpServer } from "./loopback-diff-server.js";
export { createEpisodesMcpServer } from "./loopback-episodes.js";
export { createFetchMcpServer } from "./loopback-fetch.js";
export { createFilesystemMcpServer } from "./loopback-filesystem.js";
export { createFollowupsMcpServer } from "./loopback-followups.js";
export { createHistoryMcpServer } from "./loopback-history.js";
export { createJsonMcpServer } from "./loopback-json-server.js";
export { createMathMcpServer } from "./loopback-math-server.js";
export { createMessagingMcpServer } from "./loopback-messaging.js";
export { createNotesMcpServer, deriveMirrorNoteTitle } from "./loopback-notes.js";
export type { NoteMirror, NotesMcpServerOptions } from "./loopback-notes.js";
export { createNotesRegistryMcpServer } from "./loopback-notes-registry.js";
export { createPatternsMcpServer } from "./loopback-patterns.js";
export { createProactiveMcpServer } from "./loopback-proactive.js";
export { createRegexMcpServer } from "./loopback-regex.js";
export { createRemindersMcpServer, type ReminderMirror, type RemindersMcpServerOptions } from "./loopback-reminders.js";
export { createSearchMcpServer, normaliseTimeRange } from "./loopback-search.js";
export { createStatusMcpServer } from "./loopback-status.js";
export { createTasksMcpServer } from "./loopback-tasks.js";
export { createTasksRegistryMcpServer } from "./loopback-tasks-registry.js";
export { createTextUtilsMcpServer } from "./loopback-text-utils-server.js";
export { createTimeMcpServer } from "./loopback-time-server.js";
export { createUrlMcpServer } from "./loopback-url-server.js";
export { createWebReadMcpServer } from "./loopback-web-read.js";
export { sendMessageWithApproval } from "./message-send.js";
export type { MessageApprovalGate } from "./message-send.js";
export { createNotesInvestigator } from "./notes-investigator.js";
export { NotesProviderError, NotesProviderRegistry, NotesValidationError } from "./notes-providers.js";
export type { NotesContent, NotesEntry, NotesProvider } from "./notes-providers.js";
export { AppleNotesProvider } from "./notes-providers-apple.js";
export { LocalDirNotesProvider } from "./notes-providers-local.js";
export { NotionNotesProvider } from "./notes-providers-notion.js";
export { createObjectivesListTool } from "./objectives-tool.js";
export { collectDatedNotes, createOnThisDayTool, extractNoteDate, selectOnThisDay } from "./on-this-day-tool.js";
export type { DatedNote, OnThisDayHit } from "./on-this-day-tool.js";
export { ACTIVITY_KINDS, readActivityFeed } from "./personal-activity-feed.js";
export type { ActivityKind } from "./personal-activity-feed.js";
export { summariseEpisodesRows, summariseFollowupsRows, summariseObjectivesRows, summarisePatternsFiredRows, summariseRemindersRows } from "./personal-status-summary.js";
export { createRecentActionsTool } from "./recent-actions-tool.js";
export { createRememberFactTool } from "./remember-fact-tool.js";
export { runActuatorByName } from "./run-actuator-by-name.js";
export { runDueSituationalBriefing } from "./situational-briefing-loop.js";
export { listHomeAssistantStates, parseHomeAlertChecks, performHomeActionWithApproval, readHomeAssistantState, resolveHomeAlertLine } from "./smart-home.js";
export { createHomeActionTool, createHomeEntitiesTool, createHomeStateTool } from "./smart-home-tool.js";
export { TasksProviderError, TasksProviderRegistry, TasksValidationError } from "./tasks-providers.js";
export type { Task, TasksProvider } from "./tasks-providers.js";
export { AppleRemindersProvider } from "./tasks-providers-apple.js";
export { LocalFileTasksProvider } from "./tasks-providers-local-file.js";
export { NotionTasksProvider } from "./tasks-providers-notion.js";
export { createAllowlistPathValidator } from "./upload-path-validator.js";
export { formatDailyForecast, formatRainHeadsUp, formatWeather, isoInZone, isRetriableStatus, OpenMeteoWeatherProvider, resolveForecastLine, resolveWeatherLine } from "./weather.js";
export type { CurrentWeather, DailyForecast, GeocodedLocation, WeatherProvider } from "./weather.js";
export { createWeatherTool } from "./weather-tool.js";
export { performWebActionWithApproval } from "./web-action.js";
export type { WebActionApprovalGate } from "./web-action.js";
export { createWebActionTool } from "./web-action-tool.js";
export { createWebDownloadTool } from "./web-download-tool.js";
export { extractReadableText } from "./web-readable.js";
export { assertPublicHttpUrl, extractPublicHttpUrls, isPrivateIPv4, isPrivateIPv6 } from "./web-url-guard.js";
export type { HostLookup } from "./web-url-guard.js";
export { extractImageSources, resolveImageAttachmentCandidates } from "./image-source.js";
export { createWorldTimeTool, formatTimeInZone, resolveTimezone } from "./world-time.js";
export { createDefaultLoopbackMcpServers, describeBuiltinLoopbackMcpServers } from "./loopback-defaults.js";
